# TOKEN should be output from `openssl rand -hex 32`
proxy:
  secretToken: SECRET
  https:
    enabled: true
    hosts:
      - "nlsees.rte-pangeo.org"
    type: letsencrypt
    letsencrypt:
      contactEmail: "neanderthallab@gmail.com"
  service:
    loadBalancerIP: 23.99.133.229

# GitHub Auth
auth:
  type: github
  github:
    clientId: ID
    clientSecret: SECRET
    callbackUrl: "https://nlsees.rte-pangeo.org/hub/oauth_callback"
  admin:
    access: true
    users:
      - tjcrone
      - daxsoule
