# TOKEN should be output from `openssl rand -hex 32`
proxy:
  secretToken: SECRET
  https:
    enabled: true
    hosts:
      - "nlsees.rte-pangeo.org"
    type: letsencrypt
    letsencrypt:
      contactEmail: "tjcrone@gmail.com"
  service:
    loadBalancerIP: 168.61.211.7

# GitHub Auth
#auth:
#  type: github
#  github:
#    clientId: ID
#    clientSecret: SECRET
#    callbackUrl: "https://flowmow.tjcrone.net/hub/oauth_callback"
#  admin:
#    access: true
#    users:
#      - tjcrone
