name: pangeo
channels:
  - conda-forge
  - nodefaults
dependencies:
  - av>=0.4.0
  - bokeh
  - cython
  - cytoolz
  - dask
  - dask-kubernetes
  - datashader
  - distributed
  - fastparquet
  - google-cloud-storage
  - pyviz/label/dev::geoviews
  - pyviz/label/dev::holoviews
  - pyviz/label/dev::hvplot
  - imagehash
  - intake::intake
  - intake::intake-xarray
  - ipywidgets
  - jupyter
  - jupyterlab=0.35
  - jupyterlab_launcher
  - jupyter_client
  - julia
  - lz4
  - matplotlib
  - nbserverproxy
  - netcdf4
  - numba
  - numcodecs
  - numpy
  - pandas
  - pyarrow
  - pyviz/label/dev::panel
  - pyproj
  - pytables
  - python-blosc
  - python-graphviz
  - scipy
  - scikit-image
  - xarray
  - zict
  - obspy
  - pip
  - pip:
    - numpngw
    - azure-storage-blob
    - git+https://github.com/tjcrone/pycamhd@d9cc0741f736a770dd1a19d39108026adc0deca2
    - git+https://github.com/tjcrone/driveanon
